include: package:lint/analysis_options.yaml

# Packages, that may be distributed (i.e. via pub.dev) should use the package
# version, resulting in a better pub score.
# include: package:lint/analysis_options_package.yaml

analyzer:
  exclude:
  - '**.freezed.dart'
  - '**.g.dart'

  errors:
    invalid_annotation_target: ignore
#    argument_type_not_assignable: ignore
#    invalid_assignment: ignore

# Doc: https://dart-lang.github.io/linter/lints/options/options.html
linter:
  rules:
   avoid_classes_with_only_static_members: false
#   sort_pub_dependencies: false