name: flutter_template
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.0.3
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  flutter_map: ^2.2.0
  flutter_native_splash: ^2.1.6
  flutter_svg: ^1.0.0
  get: ^4.6.5
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  intl: ^0.17.0
  just_audio: ^0.9.28
  latlong2: ^0.8.1
  loading_animation_widget: ^1.2.0+1
  location: ^4.4.0
  retrofit: ^3.0.1+1
  retrofit_generator: ^4.0.3+1
  smooth_page_indicator: ^0.3.0-nullsafety.0
  video_player: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.9.2
  build_runner: ^2.2.0
  flutter_gen_runner:

flutter:
  uses-material-design: true
#  generate: true

  assets:
    - assets/

flutter_gen:
  integrations:
    flutter_svg: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/flutterLogoPng.png

#  android_12:
#    image: assets/flutterLogoPng.png
#    icon_background_color: "#ffffff"